# conda version: 4.10.3, 4.11.0
name: nlp

channels:
  - pytorch

dependencies:
  - python=3.9
  - numpy=1.21.5
  - pandas=1.3.5
  - scikit-learn=1.0.1
  - scikit-learn-intelex
  - spacy=3.2.1
  - pytorch=1.10.1
  - cudatoolkit=11.3
  - jupyter
  - pip
  - pip:
    - tensorflow==2.7.0